### ISSUE TITLE
Endianness problems?

### ISSUE THREAD

**Issue by th-otto** [sammycage/plutovg#43] opened 2024-12-15 11:38 UTC
There seem to be some endianness problems. For example https://github.com/sammycage/plutovg/blob/3368ca48b87652c67c3359a30b2125cb81092eba/source/plutovg-surface.c#L47 takes the image data from the reader (where atleast for png, the channels are stored as R,G,B,A in that order in memory), but https://github.com/sammycage/plutovg/blob/3368ca48b87652c67c3359a30b2125cb81092eba/source/plutovg-surface.c#L271C5-L271C11 accesses that data as uint32_t, and that will get the alpha byte into the bits 24-31 only on little-endian machines.

Also, when trying to render 
![clock](https://github.com/user-attachments/assets/6e3838e0-95e2-44e7-b0bd-a6bc40cd8c78)

it renders as 

![Screenshot_20241215_122626](https://github.com/user-attachments/assets/a0ad0556-11b2-457b-ba3b-85c8fc112f32)

On a big-endian machine.

**Comment by sammycage** [comment] 2024-12-15 19:21
Thank you for bringing this up!  

I am aware of the potential endianness issues you're mentioning. The challenge I’ve faced is finding a reliable and standard way to handle endianness in a cross-platform manner.  

If you know of a robust approach or have any suggestions, I would greatly appreciate your input!

**Comment by th-otto** [comment] 2024-12-16 03:53
Thanks for your quick response.

To detect endianness, you can simply do something like
```
#include <endian.h>
#if BYTE_ORDER == BIG_ENDIAN
...
#endif
```

Or, if `<endian.h>` is not available, simply use the builtin definitions of gcc/clang
```
#if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
...
#endif
```

To swap words, you can use something like
```
uint32_t swap32(uint32_t l)
{
	return ((l >> 24) & 0xffL) | ((l << 8) & 0xff0000L) | ((l >> 8) & 0xff00L) | ((l << 24) & 0xff000000UL);
}

uint16_t swap16(uint16_t w)
{
	return (w >> 8) | (w << 8);
}
```

Note that you don't need to worry about any specialized, architecture-dependent instructions to optimize these. The compiler already has patterns to detect these, and eg. on x86 will use `bswap`

Now for the example above, i still have to figure out where that happens. It is rendered from SVG source, so is not caused by the file loaders. I guess, somewhere the wrong byte of the pixel is used as alpha value. Any idea where to look?

**Comment by sammycage** [comment] 2024-12-16 05:15
Thank you for the thoughtful explanation!  

As you pointed out earlier, the issue might indeed arise from converting RGBA to the native format and vice versa. To avoid such issues, I recommend skipping the current PNG/JPG write functions for now. Instead, after rendering, you could try converting the `plutovg_surface_t` pixel data manually and then use a library like stb_image to write it to PNG.  

By the way, which SVG library are you using? I'd like to understand more about the setup and see how it might relate to this behavior.

**Comment by th-otto** [comment] 2024-12-16 06:55
The screenshot above is already from directly displaying the surface data, without writing out any file. I think that code is correct, if it would display the data in wrong order, i would get totally wrong colors. But currently there only seems to be an issue with blending the "knobs" at 3/6/9/12.

I tried both plutosvg and LunaSVG, and get the same results.

Basically, the code using plutosvg looks like:
```
char *data;
(read svg document into data)
plutosvg_document_t *document = plutosvg_document_load_from_data(data, file_size, -1, -1, 0, NULL);
int width = plutosvg_document_get_width(document);
int height = plutosvg_document_get_height(document);
size_t image_size = (size_t)width * height * 4;
uint8_t *bmap = (uint8_t *)malloc(image_size);
plutovg_surface_t *surface = plutovg_surface_create_for_data(bmap, width, height, (size_t)width * 4);
plutovg_canvas_t *canvas = plutovg_canvas_create(surface);
plutovg_color_t bg;
plutovg_color_init_rgba32(&bg, 0xffffffff);
plutovg_surface_clear(surface, &bg);
plutosvg_document_render(document, NULL, canvas, NULL, 0, NULL);
```

The reason to do all the steps manually instead of just using `plutosvg_document_render_to_surface` is because the drawing code just needs the raw image data, and does not know about `plutovg_surface_t`.

Also note the call to plutovg_surface_clear(). This is because the window system (Atari) actually cannot handle alpha, and this should create a white background.

Code using LunaSVG looks similar:
```
char *data;
(read svg document into data)
auto svg_image = Document::loadFromData(data, file_size);
int width = svg_image->width();
int height = svg_image->height();
size_t image_size = (size_t)width * height * 4;
uint8_t *bmap = (uint8_t *)malloc(image_size);
float xScale = 1.0f;
float yScale = 1.0f;
Matrix matrix(xScale, 0, 0, yScale, 0, 0);
Bitmap bitmap(bmap, width, height, (size_t)width * 4);
bitmap.clear(0xffffffff);
svg_image->render(bitmap, matrix);
```

**Comment by sammycage** [comment] 2024-12-16 08:12
After further investigation, I discovered that the issue originates from converting RGBA image data from the stb image loader to `plutovg_surface` on a big-endian machine (this conversion works perfectly fine on little-endian systems). The `clock.svg` file uses a PNG image as a shadow for the clock knobs, and this appears to be the root cause of the issue.  

To test if this resolves the problem, you can remove the embedded image by modifying the SVG processing code as follows:  
```cpp  
char *data;  
(read svg document into data)  
auto svg_image = Document::loadFromData(data, file_size);  

svg_image->applyStyleSheet("image { display: none }"); // Hides embedded images  
svg_image->updateLayout(); // Updates the layout after applying the style  

int width = svg_image->width();  
int height = svg_image->height();  
size_t image_size = (size_t)width * height * 4;  
uint8_t *bmap = (uint8_t *)malloc(image_size);  
float xScale = 1.0f;  
float yScale = 1.0f;  
Matrix matrix(xScale, 0, 0, yScale, 0, 0);  
Bitmap bitmap(bmap, width, height, (size_t)width * 4);  
bitmap.clear(0xffffffff);  
svg_image->render(bitmap, matrix);  
```  

This code ensures that the embedded PNG image is ignored during rendering, which might help narrow down the problem.  

Let me know if the above changes fix the problem or if there’s something else you'd like me to look into for further debugging.

**Comment by th-otto** [comment] 2024-12-16 12:28
Yes, thanks, that seems to work:

![Screenshot_20241216_132031](https://github.com/user-attachments/assets/e1de958d-48f0-4e02-b033-6d91b38b747c)

I had to rebuild the library from current snapshot, because that applyStyleSheet function is not available in the v3.0.1 release.

Is something similar possible using plutosvg? I would prefer using that, since the library is only used by a plugin, and the C++ code currently requires me to link a lot of libstdc++ in (on Atari there are no really shared libs).

OTOH, plutosvg has some other limitations it seems, eg. the text is not rendered there.

**Comment by th-otto** [comment] 2024-12-16 18:11
I've come up with the attached patch now. Still have to check whether it does the right for other images like jpeg (are those really used as embedded images in SVG documents?), but atleast it should not break anything on little-endian systems.

[bigendian.patch.txt](https://github.com/user-attachments/files/18155170/bigendian.patch.txt)

**Comment by safocl** [comment] 2024-12-28 15:01
> I've come up with the attached patch now. Still have to check whether it does the right for other images like jpeg (are those really used as embedded images in SVG documents?), but atleast it should not break anything on little-endian systems.
> 
> [bigendian.patch.txt](https://github.com/user-attachments/files/18155170/bigendian.patch.txt)

for me it's a bit of a strange correction -- from my point of view it should just be used as a byte array:
```
void plutovg_convert_rgba_to_argb(unsigned char* dst, const unsigned char* src, int width, int height, int stride)
{
    static const int pixel_num_bytes = 4;
    for(int y = 0; y < height; y++) {
        const unsigned char* src_row = src + stride * y;
        unsigned char*  dst_row = dst + stride * y;
        for(int x = 0; x < width; x+=pixel_num_bytes) {
            unsigned char pixel[] = {src_row[x], src_row[x+1], src_row[x+2], src_row[x+3]};
            unsigned char a = pixel[3];
            if(a == 0) {
                for(int k = 0; k < 4; ++k){
                    dst_row[x+k] = 0;
                }
            } else {
                unsigned char b = pixel[2];
                unsigned char g = pixel[1];
                unsigned char r = pixel[0];
                if(a != 255) {
                    r = (r * a) / 255;
                    g = (g * a) / 255;
                    b = (b * a) / 255;
                }
                
                dst_row[0] = a;
                dst_row[1] = r;
                dst_row[2] = g;
                dst_row[3] = b;
            }
        }
    }
}
```

**Comment by sammycage** [comment] 2024-12-28 15:13
@safocl Thanks for your input and suggestions! The approach you shared makes sense, but do you think it would actually address the endianness issue on big-endian systems?

**Comment by th-otto** [comment] 2024-12-29 11:39
> for me it's a bit of a strange correction -- from my point of view it should just be used as a byte array:

You may think so, but it would be wrong. All routines after at work with uint32_t type, eg. all the functions from 
https://github.com/sammycage/plutovg/blob/main/source/plutovg-blend.c

So the data in the surface is expected to be in native host format.

**Comment by safocl** [comment] 2024-12-29 12:32
> @safocl Thanks for your input and suggestions! The approach you shared makes sense, but do you think it would actually address the endianness issue on big-endian systems?

endianness isn't affect into it -- the byte ordering is defined manually via an array
This issue affects integer types when they are larger than 1 byte. Only when

**Comment by safocl** [comment] 2024-12-29 14:40
> then later access it as uint32_t
where is it used in my example?

**Comment by safocl** [comment] 2024-12-29 14:43
> https://github.com/sammycage/plutovg/blob/9ef8e7842b16f26a1a27a7c1ecaa8d933e18129f/source/plutovg-blend.c#L475-L476
> expects.
> 
> Your patch would write the values in the opposite order than the current code
> 
> https://github.com/sammycage/plutovg/blob/9ef8e7842b16f26a1a27a7c1ecaa8d933e18129f/source/plutovg-surface.c#L265
> 
> does
> 
> PS.: i'm using that patch in zView (an image viewer for AtariST), and it works.

this will work fine with my code...

**Comment by safocl** [comment] 2024-12-29 14:49
> Your patch would write the values in the opposite order than the current code

no... endianess applies to both from-mem-to-integer and from-integer-to-mem placement byte order...

**Comment by th-otto** [comment] 2024-12-29 14:49
> where is it used in my example?

Not in your example, but that function generates the surface data that is used by later code and accessed as uint32_t, as already quoted above.

Not to mention that 4 single byte reads will be much slower than a single fetch.

**Comment by safocl** [comment] 2024-12-29 14:57
> Not to mention that 4 single byte reads will be much slower than a single fetch.

any benchmark info?

**Comment by safocl** [comment] 2024-12-29 15:03
> > where is it used in my example?
> 
> Not in your example, but that function generates the surface data that is used by later code and accessed as uint32_t, as already quoted above.
> 
> Not to mention that 4 single byte reads will be much slower than a single fetch.

you are talking about conversion from rgba to uint32-argb, not rgba to argb

**Comment by th-otto** [comment] 2024-12-29 15:30
Just try it out. Atleast the code above is totally broken.
- you increment x by 4 in the loop, but abort the loop with x<width, thus only converting 1/4 of the image
- dst_row[0] = a etc always writes to same location (dst_row is never incremented)

As a result, the image

![data_uri](https://github.com/user-attachments/assets/cfbba2db-e754-4a61-8e73-6ff5d2453b42)

Will be rendered as

![data_uri svg](https://github.com/user-attachments/assets/7560455b-8800-43aa-bbee-cc7709e2332e)

And when i fix that, because of the wrong byte order it will be rendered as

![data_uri svg](https://github.com/user-attachments/assets/e2156972-af45-450b-add7-130eb41c07d0)

**Comment by safocl** [comment] 2024-12-29 15:35
> * you increment x by 4 in the loop, but abort the loop with x<width, thus only converting 1/4 of the image

my example is pseudo code -- I showed how to convert without bugs from a set of bytes to a set of bytes with movement (not all function realization).

**Comment by th-otto** [comment] 2024-12-29 15:39
And i just showed you that treating the data as byte array is wrong. BTW the images where generated using svg2png on linux, not on a big-endian machine.

**Comment by safocl** [comment] 2024-12-29 15:54
> And i just showed you that treating the data as byte array is wrong. BTW the images where generated using svg2png on linux, not on a big-endian machine.

data format don't depend for endianess... For this memory byte order is constant.
you you suggest converting as  [i said above](https://github.com/sammycage/plutovg/issues/43#issuecomment-2564751648)
`dst` is `uint8*` , not `uint32*`

**Comment by th-otto** [comment] 2024-12-29 16:00
I'm giving up. Just implement a real version of your code, then test it with SVGs with embedded images (like the one above), and see how things go wrong.

**Comment by safocl** [comment] 2024-12-29 16:11
> I'm giving up. Just implement a real version of your code, then test it with SVGs with embedded images (like the one above), and see how things go wrong.

return your words only in two cases - either if the incoming **data** has already been converted by applying **endianess** (but then they should be as `uint32*`), or the output data will be interpreted already taking into account **endianess** (but then they should be as `uint32*`).

**Comment by sammycage** [comment] 2024-12-29 22:33
@safocl Each pixel is a 32-bit quantity, with the alpha channel in the upper 8 bits, followed by red, green, and blue. The 32-bit quantities are stored in the native-endian format of the machine. Pre-multiplied alpha is used. In summary, the PlutoVG surface format is BGRA (pre-multiplied) on little-endian machines and ARGB (pre-multiplied) on big-endian machines. Therefore, accessing pixels directly by bytes without considering the platform's native endianness is unreliable and does not resolve the endianness issue.

**Comment by sammycage** [comment] 2024-12-29 22:41
@th-otto Hey there!  

With my humble logic skills, I came up with this code snippet:  

```c  
void plutovg_convert_argb_to_rgba(unsigned char* dst, const unsigned char* src, int width, int height, int stride)  
{  
    for (int y = 0; y < height; y++) {  
        const uint32_t* src_row = (const uint32_t*)(src + stride * y);  
        uint32_t* dst_row = (uint32_t*)(dst + stride * y);  
        for (int x = 0; x < width; x++) {  
            uint32_t pixel = src_row[x];  
#if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__  
            uint32_t a = (pixel >> 0) & 0xFF;  
            uint32_t r = (pixel >> 8) & 0xFF;  
            uint32_t g = (pixel >> 16) & 0xFF;  
            uint32_t b = (pixel >> 24) & 0xFF;  
#else  
            uint32_t b = (pixel >> 0) & 0xFF;  
            uint32_t g = (pixel >> 8) & 0xFF;  
            uint32_t r = (pixel >> 16) & 0xFF;  
            uint32_t a = (pixel >> 24) & 0xFF;  
#endif  
            if (a == 0) {  
                dst_row[x] = 0x00000000;  
            } else {  
                if (a != 255) {  
                    r = (r * 255) / a;  
                    g = (g * 255) / a;  
                    b = (b * 255) / a;  
                }  
#if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__  
                dst_row[x] = (r << 24) | (g << 16) | (b << 8) | a;  
#else  
                dst_row[x] = (a << 24) | (b << 16) | (g << 8) | r;  
#endif  
            }  
        }  
    }  
}  

void plutovg_convert_rgba_to_argb(unsigned char* dst, const unsigned char* src, int width, int height, int stride)  
{  
    for (int y = 0; y < height; y++) {  
        const uint32_t* src_row = (const uint32_t*)(src + stride * y);  
        uint32_t* dst_row = (uint32_t*)(dst + stride * y);  
        for (int x = 0; x < width; x++) {  
            uint32_t pixel = src_row[x];  
#if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__  
            uint32_t a = (pixel >> 0) & 0xFF;  
            uint32_t b = (pixel >> 8) & 0xFF;  
            uint32_t g = (pixel >> 16) & 0xFF;  
            uint32_t r = (pixel >> 24) & 0xFF;  
#else  
            uint32_t r = (pixel >> 0) & 0xFF;  
            uint32_t g = (pixel >> 8) & 0xFF;  
            uint32_t b = (pixel >> 16) & 0xFF;  
            uint32_t a = (pixel >> 24) & 0xFF;  
#endif  
            if (a == 0) {  
                dst_row[x] = 0x00000000;  
            } else {  
                if (a != 255) {  
                    r = (r * a) / 255;  
                    g = (g * a) / 255;  
                    b = (b * a) / 255;  
                }  
#if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__  
                dst_row[x] = (b << 24) | (g << 16) | (r << 8) | a;  
#else  
                dst_row[x] = (a << 24) | (r << 16) | (g << 8) | b;  
#endif  
            }  
        }  
    }  
}  
```  

Could you please test it on your big-endian machine and let me know if it works? 🙏 Thanks in advance! 😊

**Comment by sammycage** [comment] 2024-12-29 23:32
@th-otto Thank you for reporting this issue and providing the patch. I’m glad to hear that it’s working on your fork! After reviewing the patch, I realized that the endian condition only applies to RGBA pixel data from/to the stb image loader/writer. Handling endianness is always tricky, but I think I’m close to wrapping this up for now. I’m going to close this issue, but I’ll reopen it once I’m ready to fully support it (whenever I get my hands on a big-endian machine). Thanks again for your input!

**Comment by safocl** [comment] 2024-12-30 00:16
> The 32-bit quantities are stored in the native-endian format of the machine

that is, the same data, according to your statements, will give different results on different systems? How, for example, can a picture predict on which system it will be stored and viewed?

**Comment by safocl** [comment] 2024-12-30 00:18
> does not resolve the endianness issue.

Input data is a pointer to bytes, output data is the same...

**Comment by safocl** [comment] 2024-12-30 00:36
> @safocl Each pixel is a 32-bit quantity, with the alpha channel in the upper 8 bits, followed by red, green, and blue. The 32-bit quantities are stored in the native-endian format of the machine. Pre-multiplied alpha is used. Therefore, accessing pixels directly by bytes without considering the platform's native endianness is unreliable and does not resolve the endianness issue.

the byte order is important for registers, not raw memory... when you use raw memory as uint32 it uses the byte order, but if not use this as uint32 then native byte order is not use.

input raw memory:
[ 0 ] [ 1 ] [ 2 ] [ 3 ] | [ 0 ] [ 1 ] [ 2 ] [ 3 ] | [ 0 ] [ 1 ] [ 2 ] [ 3 ] | [ 0 ] [ 1 ] [ 2 ] [ 3 ] ... [ 0 ] [ 1 ] [ 2 ] [ 3 ]
[ r ] [ g ] [ b ] [ a ] | [ r ] [ g ] [ b ] [ a ] | [ r ] [ g ] [ b ] [ a ] | [ r ] [ g ] [ b ] [ a ] ... [ r ] [ g ] [ b ] [ a ]

if use my method then the following conclusion will be obtained:
[ 0 ] [ 1 ] [ 2 ] [ 3 ] | [ 0 ] [ 1 ] [ 2 ] [ 3 ] | [ 0 ] [ 1 ] [ 2 ] [ 3 ] | [ 0 ] [ 1 ] [ 2 ] [ 3 ] ... [ 0 ] [ 1 ] [ 2 ] [ 3 ]
[ a ] [ r ] [ g ] [ b ] | [ a ] [ r ] [ g ] [ b ] | [ a ] [ r ] [ g ] [ b ] | [ a ] [ r ] [ g ] [ b ] ... [ a ] [ r ] [ g ] [ b ]
and the byte order will not affect this.

but if input memory is already have native endian byte order (library do it) -- this issue is incorrect.

**Comment by sammycage** [comment] 2024-12-30 00:45
Here's a simple C code that demonstrates the endianess of the system by printing the byte order of an integer:

```c
#include <stdio.h>

int main() {
    int num = 1;  // Any non-zero number
    unsigned char *bytePtr = (unsigned char*)&num;

    printf("The byte order of the integer 1 is: ");

    if (bytePtr[0] == 1) {
        printf("Little Endian\n");
    } else {
        printf("Big Endian\n");
    }

    // Print the actual byte order for demonstration
    printf("Bytes of the number (in memory): ");
    for (int i = 0; i < sizeof(num); i++) {
        printf("%02x ", bytePtr[i]);
    }
    printf("\n");

    return 0;
}
```

### Expected Output:
- On a little-endian machine (e.g., most x86 systems), the output will be:
  ```log
  The byte order of the integer 1 is: Little Endian
  Bytes of the number (in memory): 01 00 00 00
  ```

- On a big-endian machine, the output will be:
  ```log
  The byte order of the integer 1 is: Big Endian
  Bytes of the number (in memory): 00 00 00 01
  ```

**Comment by sammycage** [comment] 2024-12-30 01:07
> The byte order is important for registers, not raw memory...

This is somewhat misleading. The byte order (endianness) is important for **both registers and raw memory**, as the system must know how to interpret multi-byte data. When accessing memory directly, the endianness still affects how the bytes are read and written, even if the data is stored in a register.

You need to account for whether the machine is little-endian or big-endian when accessing the raw memory, as the machine will store the data in the native byte order, and this affects how you interpret the bytes.

**Comment by safocl** [comment] 2024-12-30 01:07
@sammycage , Yes, this example is as I described above.
but it use `int32`, not `uint8[4]`

**Comment by safocl** [comment] 2024-12-30 01:11
> > The byte order is important for registers, not raw memory...
> 
> This is somewhat misleading. The byte order (endianness) is important for **both registers and raw memory**, as the system must know how to interpret multi-byte data. When accessing memory directly, the endianness still affects how the bytes are read and written, even if the data is stored in a register.
> 
> You need to account for whether the machine is little-endian or big-endian when accessing the raw memory, as the machine will store the data in the native byte order, and this affects how you interpret the bytes.

No, that is not true. Until the memory is interpreted as a multi-byte number, it will not be endian dependent.

**Comment by sammycage** [comment] 2024-12-30 01:18
> No, that is not true. Until the memory is interpreted as a multi-byte number, it will not be endian dependent.

Nice point. Because in https://github.com/sammycage/plutovg/blob/main/source/plutovg-blend.c, the surface data is interpreted as a `uint32_t`, which makes it endian-dependent when working with the pixel data.

**Comment by safocl** [comment] 2024-12-30 01:28
> > No, that is not true. Until the memory is interpreted as a multi-byte number, it will not be endian dependent.
> 
> Nice point. Because in https://github.com/sammycage/plutovg/blob/main/source/plutovg-blend.c, the surface data is interpreted as a `uint32_t`, which makes it endian-dependent when working with the pixel data.

https://github.com/sammycage/plutovg/blob/9ef8e7842b16f26a1a27a7c1ecaa8d933e18129f/source/plutovg-blend.c#L26
then you might be better off using `uint32*` instead of `uint8*` (to eliminate misperception of the code).
and here (and in the same cases):
https://github.com/sammycage/plutovg/blob/3368ca48b87652c67c3359a30b2125cb81092eba/source/plutovg-surface.c#L271

**Comment by sammycage** [comment] 2024-12-30 01:39
@safocl Thank you for your time and suggestions.

Using `unsigned char` for surface pixel data is consistent with how other graphics libraries handle it. However, I agree that there could be confusion regarding the interpretation of byte order. I will update the documentation to properly explain the surface format and clarify this aspect.

Thanks again for your valuable input!

**Comment by th-otto** [comment] 2024-12-30 10:37
> (whenever I get my hands on a big-endian machine).

If you want, you can try out ARAnyM (an Atari Falcon emulator). A french guy has made a tutorial some time ago to get it up: 

https://www.youtube.com/watch?v=GOkDuLmgWFo

Snapshots of the viewer i mentioned are available at https://tho-otto.de/snapshots/zview/zview-020-latest.zip

**Comment by sammycage** [comment] 2024-12-30 10:38
@th-otto I have managed to fix this issue with the latest [commit](https://github.com/sammycage/plutovg/commit/e026d0ac7ba29818cd0a73548b9903eef7da50c1). It turns out that the stb image loader/writer image data is endian-independent, as it uses an RGBA byte sequence. Accessing the data byte by byte works as @safocl suggested. @th-otto Please test it on your big-endian machine and let me know if it works for you.

**Comment by th-otto** [comment] 2024-12-30 10:54
Yes, your fix seems to work too. For performance reason, i may still stick to my version ;) (that poor Atari is a retro computer from the 90ies, and every cycle counts, especially for memory accesses)

**Comment by sammycage** [comment] 2024-12-30 11:27
That's lovely! 😊 Good luck with your current version, and rest assured that the rest of the code is highly optimized to run smoothly on your poor Atari 🥺. I’m sure your Atari will appreciate the extra care! 😄

**Closed by sammycage** 2024-12-30 11:27 UTC
Labels: enhancement
